/**
 * UI-Table-Annotator API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TableCellDTO } from "./models";

export interface TableRowDTO {
    tableId?: string;
    rowEntries?: TableCellDTO;
    question?: string;
    row?: number;
    answerColumn?: number;
    content?: string
}
